# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: ser
  password: 123456
  host: localhost
  port: 5432

development:
  <<: *default
  database: rails_course_development

test:
  <<: *default
  database: rails_course_test
